### ISSUE TITLE
Update MacOS to Mojave, then vim get error with powerline

### ISSUE THREAD

**Issue by DinoStray** [powerline/powerline#1947]
error as follow: 
```
Error detected while processing /Users/vvqboy/.vimrc:
line    8:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/vvqboy/Library/Python/2.7/lib/python/site-packages/powerline/__init__.py", line 11, in <module>
    from powerline.lib.config import ConfigLoader
  File "/Users/vvqboy/Library/Python/2.7/lib/python/site-packages/powerline/lib/config.py", line 11, in <module>
    from powerline.lib.threaded import MultiRunnedThread
  File "/Users/vvqboy/Library/Python/2.7/lib/python/site-packages/powerline/lib/threaded.py", line 7, in <module>
    from powerline.lib.monotonic import monotonic
  File "/Users/vvqboy/Library/Python/2.7/lib/python/site-packages/powerline/lib/monotonic.py", line 19, in <module>
    import ctypes
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 555, in <module>
    _reset_cache()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 279, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError
line    9:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'powerline_setup' is not defined
line   10:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'powerline_setup' is not defined
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/Users/vvqboy/Library/Python/2.7/lib/python/site-packages/powerline/__init__.py", line 11, in <module>
    from powerline.lib.config import ConfigLoader
  File "/Users/vvqboy/Library/Python/2.7/lib/python/site-packages/powerline/lib/config.py", line 11, in <module>
    from powerline.lib.threaded import MultiRunnedThread
  File "/Users/vvqboy/Library/Python/2.7/lib/python/site-packages/powerline/lib/threaded.py", line 7, in <module>
    from powerline.lib.monotonic import monotonic
  File "/Users/vvqboy/Library/Python/2.7/lib/python/site-packages/powerline/lib/monotonic.py", line 19, in <module>
    import ctypes
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 555, in <module>
    _reset_cache()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 279, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError
An error occurred while importing powerline module.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
Vim: Caught deadly signal SEGV

Vim: Finished.
[1]    7428 segmentation fault  vi .vimrc
```

**Comment by DinoStray** [comment]
vimrc as follow:
```
set rtp+=/Users/vvqboy/Library/Python/2.7/lib/python/site-packages/powerline/bindings/vim

" These lines setup the environment to show graphics and colors correctly.
set nocompatible
set t_Co=256
 
let g:minBufExplForceSyntaxEnable = 1
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup
 
if ! has('gui_running')
   set ttimeoutlen=10
   augroup FastEscape
      autocmd!
      au InsertEnter * set timeoutlen=0
      au InsertLeave * set timeoutlen=1000
   augroup END
endif
 
set laststatus=2 " Always display the statusline in all windows
set guifont=Inconsolata\ for\ Powerline:h14
set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)

set nu
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
```

**Comment by DinoStray** [comment]
I try to 
```
pip install --upgrade --force-reinstall  --user powerline-status
```
then still get error
```
Vim: Caught deadly signal SEGV
Error detected while processing /Users/vvqboy/.vimrc:Vim: Finished.

line    8:
Exception MemoryError: MemoryError() in <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored
[1]    1788 segmentation fault  vi .vimrc
```

**Comment by DinoStray** [comment]
python --version
Python 2.7.10

**Comment by anirrudh** [comment]
Hey, same error here. Tried a couple fixes using brew (thought it may be a sym link issue), but all seems to be well there, and my pyenv seems fine. 

Here is the err I get to be doubly sure (and this happened after Moajve update as well for me):

```MemoryError
An error occurred while importing powerline module.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
possible solutions.
Error detected while processing 
...
line  157:
Traceback (most recent call last):
  File "<string>", line 53, in <module>
  File "<string>", line 9, in powerline_troubleshoot
  File "/Users/.../Library/Python/2.7/lib/python/site-packages/powerline/__init__.py", line 11, in <module>
    from powerline.lib.config import ConfigLoader
  File "/Users/.../Library/Python/2.7/lib/python/site-packages/powerline/lib/config.py", line 11, in <module>
    from powerline.lib.threaded import MultiRunnedThread
  File "/Users/.../Library/Python/2.7/lib/python/site-packages/powerline/lib/threaded.py", line 7, in <module>
    from powerline.lib.monotonic import monotonic
  File "/Users/.../Library/Python/2.7/lib/python/site-packages/powerline/lib/monotonic.py", line 19, in <module>
    import ctypes
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 555, in <module>
    _reset_cache()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 279, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError
```

**Comment by anirrudh** [comment]
Interestingly, pointing the path to the _actual_ powerline.vim file will load vim fine and won't throw any errors, but does not load the powerline either. 

`/Library/Python/2.7/site-packages/powerline/powerline/bindings/vim/plugins/powerline.vim`

Vim happily chugs away. Additionally, my tmux conf loads powerline just fine, so I think this is an issue specific to vim-powerline. I'll do some investigation and get back to you.

**Comment by ZyX-I** [comment]
Does Python version Vim was compiled with match Python version Vim is actually using? MemoryError and then SEGV while importing ctypes indicates problems with Python installation, not powerline problems. You should get the same problem (at least, MemoryError, though I am unsure what it actually means: perhaps, memory allocator returning NULL?) if you disable powerline and do `:python import ctypes` in vim.

**Comment by anirrudh** [comment]
Bingo, that did not work. However, it was working absolutely fine before the MacOS Mojave Update.

**Comment by zzswang** [comment]
Error +1 after updated to mojave

```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/Users/zzs/Library/Python/2.7/lib/python/site-packages/powerline/__init__.py", line 11, in <module>
    from powerline.lib.config import ConfigLoader
  File "/Users/zzs/Library/Python/2.7/lib/python/site-packages/powerline/lib/config.py", line 11, in <module>
    from powerline.lib.threaded import MultiRunnedThread
  File "/Users/zzs/Library/Python/2.7/lib/python/site-packages/powerline/lib/threaded.py", line 7, in <module>
    from powerline.lib.monotonic import monotonic
  File "/Users/zzs/Library/Python/2.7/lib/python/site-packages/powerline/lib/monotonic.py", line 19, in <module>
    import ctypes
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 555, in <module>
    _reset_cache()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 279, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError
An error occurred while importing powerline module.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
possible solutions.
Error detected while processing /usr/local/lib/python2.7/site-packages/powerline/bindings/vim/plugin/powerline.vim:
line  157:
Traceback (most recent call last):
  File "<string>", line 53, in <module>
  File "<string>", line 9, in powerline_troubleshoot
  File "/Users/zzs/Library/Python/2.7/lib/python/site-packages/powerline/__init__.py", line 11, in <module>
    from powerline.lib.config import ConfigLoader
  File "/Users/zzs/Library/Python/2.7/lib/python/site-packages/powerline/lib/config.py", line 11, in <module>
    from powerline.lib.threaded import MultiRunnedThread
  File "/Users/zzs/Library/Python/2.7/lib/python/site-packages/powerline/lib/threaded.py", line 7, in <module>
    from powerline.lib.monotonic import monotonic
  File "/Users/zzs/Library/Python/2.7/lib/python/site-packages/powerline/lib/monotonic.py", line 19, in <module>
    import ctypes
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 555, in <module>
    _reset_cache()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 279, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError
Press ENTER or type command to continue
```

**Comment by anirrudh** [comment]
> Does Python version Vim was compiled with match Python version Vim is actually using? MemoryError and then SEGV while importing ctypes indicates problems with Python installation, not powerline problems. You should get the same problem (at least, MemoryError, though I am unsure what it actually means: perhaps, memory allocator returning NULL?) if you disable powerline and do `:python import ctypes` in vim.

So it was working fine _just before_ the upgrade. My zsh and tmux setup are working fine using the other bindings as well. 

When running the command: `:python import ctypes` in vim, I get the same error (the CTYPE error) as shown above. I wonder what Apple changed in the shipped version of Apple-Python, or really, if they changed anything. I'll try a little later tonight and revert back.

**Comment by ZyX-I** [comment]
Zsh and tmux use Python interpreter in a separate process (unless you are using zsh with libzpython, but there is no tmux equivalent). Vim is either loading Python as a dynamic library via dlopen or just links with it which is more fragile, and should you ever change Python version you need to recompile Vim with the new one or risk running into problems. I am not sure how differences in versions may cause ctypes import to malfunction that late (normally you would not get `:python` running at all, or it may sometimes crash), but it is one possible explanation.

Another one is the difference between system and homebrew Python version. I have no Mac and can’t say which one Vim is supposed to load of the two and how exactly it does the feat, but this is another common explanation of problems with (app(vim, etc))+Python setup on Mac, and it may cause various kinds of errors on import.

**Comment by anirrudh** [comment]
@ZyX-I oooo got it. Do you have a doc off-hand describing the process? I had no idea that was how it worked. 

Let me recompile vim with the system version and see what happens!

**Comment by anirrudh** [comment]
SOLUTION!!

Step 1) Figure out your current vim version. Mine was _not_ compiled with homebrew, but was the default system version, which was recompiled by Apple for the Mojave release (looking at the date). I think that's correct, based on the compile date, but correct me if I am wrong. Run `vim --version` and you should see that it has been compiled by `root@apple.com`.

Step 2) I chose to uninstall the brew'd version of python@2, and installed python via brew (it installs 3.7.0 by default at the time of writing), and _did not_ link it. Just left it there. Read some forum stating that it doesn't compile with brew python unless it is installed. @ZyX-I maybe you know more about this?

Step 3) After `brew install python`, `brew install vim`. Let that install. Then, run `/usr/local/bin/vim --version` and make sure the python3 has a '+' sign next to it. Restart your shell, and then the ./vimrc should read: `/Library/Python/2.7/site-packages/powerline/powerline/bindings/vim/` or whatever dir you are looking at. Source vimrc. 

Step 4) Be happy that powerline is working and get back to actually programming :p

**Comment by zhongruizhi** [comment]
I have the same error when I upgraded to Mojave.
`line   63:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xxx/Library/Python/2.7/lib/python/site-packages/powerline/__init__.py", line 11, in <module>
    from powerline.lib.config import ConfigLoader
  File "/Users/xxx/Library/Python/2.7/lib/python/site-packages/powerline/lib/config.py", line 11, in <module>
    from powerline.lib.threaded import MultiRunnedThread
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/powerline/lib/threaded.py", line 7, in <module>
    from powerline.lib.monotonic import monotonic
  File "/Users/xxx/Library/Python/2.7/lib/python/site-packages/powerline/lib/monotonic.py", line 19, in <module>
    import ctypes
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 555, in <module>
    _reset_cache()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 279, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError
line   64:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'powerline_setup' is not defined
line   65:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'powerline_setup' is not defined`
After I rolled back to system default python, I still got the same error.

**Comment by zhongruizhi** [comment]
> @zhongruizhi did you try what I suggested above? I posted my solution and that fixed it for me!

thanks, but it seems like your solution is not quite fit for my condition. I'm not using brew, and I'm using system's default python(2.7.10) and vim.(+python/dyn -python3) .

**Comment by Era2016** [comment]
@anirrudh it really works for me, a good solution, thanks very much

**Comment by anirrudh** [comment]
@zhongruizhi So I used to have the standard vim version provided by Apple as well, but that seems to be broken for powerline, the only fix seems to be to install vim via brew -- and as for python versions, I address that in my post above, but you need to make sure that +python3 is a thing, not +python/dyn, which was exactly what my apple provided vim had!

**Comment by DinoStray** [comment]
This done for me:
brew remove csshx
Then add the tap:
brew tap parera10/csshx
Then install it again:
brew install parera10/csshx/csshx
ref: https://github.com/brockgr/csshx/issues/94

**Comment by hexid26** [comment]
@anirrudh Thank you for figuring out the details. And it works.

**Comment by BetaBeauty** [comment]
I found a solution and possible reason:
_reset_cache() in file:  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py get memory error. And I jump to this function and found such code:

```
def _reset_cache():
    _pointer_type_cache.clear()
    _c_functype_cache.clear()
    if _os.name in ("nt", "ce"):
        _win_functype_cache.clear()
    # _SimpleCData.c_wchar_p_from_param
    POINTER(c_wchar).from_param = c_wchar_p.from_param
    # _SimpleCData.c_char_p_from_param
    POINTER(c_char).from_param = c_char_p.from_param
    _pointer_type_cache[None] = c_void_p
    # XXX for whatever reasons, creating the first instance of a callback
    # function is needed for the unittests on Win64 to succeed.  This MAY
    # be a compiler bug, since the problem occurs only when _ctypes is
    # compiled with the MS SDK compiler.  Or an uninitialized variable?
    CFUNCTYPE(c_int)(lambda: None)
```
As you see, the CFUNCTYPE function line is added for Win64 unittest for whatever reason. And this is the error line! So I comment the line and re run vim, then no errors with powerline.

More:
The file is system read-only file. You may run command `csrutil disable` in mac recovery mode(press Command+R when booting up) to disable System Integrity Protection. After reboot, you can edit this file and comment this line use sudo permission.

**Comment by BetaBeauty** [comment]
I found the reason and a solution i think more elegent:
CFUNCTYPE at _reset_cache() function in file: 
`/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py` 
get memory error.
Then I jumped to this file and found such code:

```
265 def _reset_cache():
266     _pointer_type_cache.clear()
267     _c_functype_cache.clear()
268     if _os.name in ("nt", "ce"):
269         _win_functype_cache.clear()
270     # _SimpleCData.c_wchar_p_from_param
271     POINTER(c_wchar).from_param = c_wchar_p.from_param
272     # _SimpleCData.c_char_p_from_param
273     POINTER(c_char).from_param = c_char_p.from_param
274     _pointer_type_cache[None] = c_void_p
275     # XXX for whatever reasons, creating the first instance of a callback
276     # function is needed for the unittests on Win64 to succeed.  This MAY
277     # be a compiler bug, since the problem occurs only when _ctypes is
278     # compiled with the MS SDK compiler.  Or an uninitialized variable?
279     CFUNCTYPE(c_int)(lambda: None)
```
As you can see, CFUNCTYPE function at line 279 is added by unittest on Win64 for whatever reasons. For mac user, this line is useless and lead to memory error on macOS. So I comment out line 279, and rerun vim, there is no errors with powerline.

More Details:
The `__init__.py` file is system read-only file, and you need to run command `csrutil disable` in mac recovery mode(press command+R when booting up) to disable System Integrity Protection. After reboot, you can edit this file use root permission.

**Comment by Joshua-Chang** [comment]
brew install vim --with-lua --with-override-system-vi
and restart shell , fixed


https://github.com/Valloric/YouCompleteMe/issues/3165#issuecomment-425616700

**Comment by zzswang** [comment]
Thank you @Joshua-Chang 

It worked for me

**Comment by whenever77** [comment]
thank you @Joshua-Chang 
vim is ok, but **vi still wrong** 
`Vim: Caught deadly signal SEGV
Error detected while processing function <SNR>70_PollServerReady[7]..<SNR>70_Pyeval:Vim: Finished.

line    4:
Exception MemoryError: MemoryError() in <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored
Segmentation fault: 11`

**Comment by macgyver** [comment]
> vim is ok, but **vi still wrong**

maybe there's a better resolution out there but I fixed that one by adding `alias vi="vim"` into my shell rc file

**Comment by kyriejoshua** [comment]
I have the same problem with @whenever77  when i use commad `git commit --amend`.

**Comment by zzswang** [comment]
@kyriejoshua 

try @Joshua-Chang 's suggestion, it works for me.

**Comment by kyriejoshua** [comment]
> try @Joshua-Chang 's suggestion, it works for me.

I tried.
 It works when i use vim directly, but it is still wrong when i use command `git commit --amend` or try to fix conflicts in command line.

**Comment by josephtyler** [comment]
@kyriejoshua Mind sharing the solution?

**Comment by kyriejoshua** [comment]
It's my solution. @josephtyler 

`cd ~/.vim/bundle/YouCompleteMe`
`git pull`
`git submodule update --init --recursive.`
`python install.py`

and restart shell , fixed

**Comment by puremourning** [comment]
For YCM users, please use [YCM contacts](https://github.com/Valloric/YouCompleteMe#contact)

We are tracking a similar issue with system Vim here: https://github.com/Valloric/YouCompleteMe/issues/3271

Spoiler alert: I think it is a Mojave thing not a YCM thing.

**Comment by davidjb** [comment]
For me, the issue started appearing after a "critical update" was installed by Mojave (eg I've been on Mojave for ages with vim/powerline working fine).  Turns out it was simply a case of the wrong `vim` being used (eg `/usr/bin/vim`, Apple's built-in vim) rather than my vim from `/usr/local/bin/vim`.  It was just a case of fixing my `PATH`; the update presumably reordered it.

**Comment by colindjk** [comment]
I just started using a mac with a fresh install of Mojave and got this issue, it should be noted that I am using python3.7. 

I solved it by doing the following:
```
brew install vim
echo "alias vim=/usr/local/Cellar/vim/<VIM_VERSION>/bin/vim" >> ~/.bash_profile
```
Just replace VIM_VERSION with the version of vim that brew installed on the first line.

**Comment by jwoytek** [comment]
Can add another confirmation that this is related to the macOS Mojave update. I'm going to have to do some comparison work with another machine that has NOT been updated yet to see what system libraries changed. I'm sure it is something that changed in the default python 2.7(.10) installation or something with a related library.

**Comment by Jefferson-Faseler** [comment]
Had this same issue coming from bash to zsh, what fixed it for me was exporting my `PATH`. `export PATH=$HOME/bin:/usr/local/bin:$PATH`

I already had python 3.7.3, vim (the version included from macvim compiled by travis@Traviss-Mac.local), and already had Mojave. Was only making transition to zsh.
